import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react'

export default function Home() {
  const router = useRouter()
  const [loggedIn, setLoggedIn] = useState<boolean | undefined>(undefined)

  useEffect(() => {
    (async () => {
      console.log('try-login')
      const {logged_in}= await fetch('/api/auth').then(res => res.json())
      if (!logged_in) {
        router.push('/login')
        return
      }
      setLoggedIn(true)
    })().catch(() => {
      router.push('/login')
    });
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          miniflux client
        </h1>
        {loggedIn === undefined ? (
          <div>
            loading...
          </div>
        ) : (
          <div>
            logged in!
          </div>
        )}
      </main>
    </div>
  )
}
